version: "3.8"

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  web:
    build: .
    image: zoubairmabrouk/fastapi-ollama:latest
    depends_on:
      - ollama
    environment:
      - OL_BASE_URL=http://ollama:11434/v1
      - OL_API_KEY=${OL_API_KEY}
    ports:
      - "8000:8000"

volumes:
  ollama_data: